export const badges = [
  { id: 'first-session', name: 'First Steps', description: 'Complete your first study session', icon: '🌱', check: (stats) => stats.totalSessions >= 1 },
  { id: 'ten-cards', name: 'Card Collector', description: 'Review 10 flashcards', icon: '🃏', check: (stats) => stats.totalCardsReviewed >= 10 },
  { id: 'fifty-cards', name: 'Card Master', description: 'Review 50 flashcards', icon: '🎴', check: (stats) => stats.totalCardsReviewed >= 50 },
  { id: 'hundred-cards', name: 'Card Legend', description: 'Review 100 flashcards', icon: '👑', check: (stats) => stats.totalCardsReviewed >= 100 },
  { id: 'first-quiz', name: 'Quiz Taker', description: 'Complete your first quiz', icon: '📝', check: (stats) => stats.totalQuizzes >= 1 },
  { id: 'perfect-quiz', name: 'Perfect Score', description: 'Get 100% on a quiz', icon: '💯', check: (stats) => stats.perfectQuizzes >= 1 },
  { id: 'streak-3', name: 'On a Roll', description: '3-day study streak', icon: '🔥', check: (stats) => stats.currentStreak >= 3 },
  { id: 'streak-7', name: 'Week Warrior', description: '7-day study streak', icon: '⚡', check: (stats) => stats.currentStreak >= 7 },
  { id: 'streak-14', name: 'Fortnight Focus', description: '14-day study streak', icon: '🏆', check: (stats) => stats.currentStreak >= 14 },
  { id: 'streak-30', name: 'Monthly Master', description: '30-day study streak', icon: '🌟', check: (stats) => stats.currentStreak >= 30 },
  { id: 'level-5', name: 'Knowledge Sprout', description: 'Reach level 5', icon: '🌿', check: (stats) => stats.level >= 5 },
  { id: 'level-10', name: 'Brain Explorer', description: 'Reach level 10', icon: '🧠', check: (stats) => stats.level >= 10 },
  { id: 'level-20', name: 'Memory Master', description: 'Reach level 20', icon: '🎓', check: (stats) => stats.level >= 20 },
  { id: 'first-game', name: 'Game On', description: 'Play your first study game', icon: '🎮', check: (stats) => stats.totalGames >= 1 },
  { id: 'five-games', name: 'Gamer', description: 'Play 5 study games', icon: '🕹️', check: (stats) => stats.totalGames >= 5 },
  { id: 'first-import', name: 'Note Taker', description: 'Import your first set of notes', icon: '📸', check: (stats) => stats.totalImports >= 1 },
  { id: 'night-owl', name: 'Night Owl', description: 'Study after 9 PM', icon: '🦉', check: (stats) => stats.studiedLateNight },
  { id: 'early-bird', name: 'Early Bird', description: 'Study before 7 AM', icon: '🐦', check: (stats) => stats.studiedEarlyMorning },
  { id: 'overload-complete', name: 'Cram Champion', description: 'Complete an Overload session', icon: '💪', check: (stats) => stats.overloadSessions >= 1 },
  { id: 'pacing-complete', name: 'Steady Pacer', description: 'Complete a Pacing study plan', icon: '🏃', check: (stats) => stats.pacingCompleted >= 1 },
];
